<?php

return [
    'permissions' => [
        'dashboard' => [
            'dashboard.view',
            'total_member.total_member_view',
            'total_student.total_student_view',
            'total_school_manager.total_school_manager_view',
            'total_franchise.total_franchise_view',
            'active_franchise.active_franchise_view',
            'inactive_franchise.inactive_franchise_view',
            'approve_franchise.approve_franchise_view',
            'unapprove_franchise.unapprove_franchise_view',
            'total_leads.total_leads_view',
            'total_allocated_leads.total_allocated_leads_view',
            'total_non_allocated_leads.total_non_allocated_leads_view',
            'approve_counselor.approve_counselor_view',
            'total_agent.total_agent_view',
            'total_university.total_university_view',
            'total_program.total_program_view',
            'total_application.total_application_view',
            'total_unapprove_universties.total_unapprove_universties_view',
            'total_unapprove_program.total_unapprove_program_view',
            'total_unapprove_counceler.total_unapprove_counceler_view',
            'total_approve_counceler.total_approve_counceler_view',
            'total_assigned_leads.total_assigned_leads_view'
        ],
        'admin_user' => [
            'admin_user.create',
            'admin_user.view',
            'admin_user.update',
            'admin_user.delete',
        ],
        'role_permissions' => [
            'role_permissions.create',
            'role_permissions.view',
            'role_permissions.update',
            'role_permissions.delete',
        ],
        'profile' => [
            'profile.view',
            'profile.update',
        ],
        'leads_dashboard' => [
            'leads_dashboard.create',
            'leads_dashboard.view',
            'leads_dashboard.update',
            'leads_dashboard.delete',
        ],
        'add_leads' => [
            'add_leads.create',
            'add_leads.view',
            'add_leads.update',
            'add_leads.delete',
        ],
        'bulk_upload' => [
            'bulk_upload.create',
            'bulk_upload.view',
            'bulk_upload.update',
            'bulk_upload.delete',
        ],
        'pending_lead' => [
            'pending_lead.create',
            'pending_lead.view',
            'pending_lead.update',
            'pending_lead.delete',
        ],
        'assigned_lead' => [
            'assigned_lead.create',
            'assigned_lead.view',
            'assigned_lead.update',
            'assigned_lead.delete',
        ],
        'latest_updated_leads' => [
            'latest_updated_leads.create',
            'latest_updated_leads.view',
            'latest_updated_leads.update',
            'latest_updated_leads.delete',
        ],
        'oel_360' => [
            'oel_360.create',
            'oel_360.view',
            'oel_360.update',
            'oel_360.delete',
        ],
        'leads_list' => [
            'leads_lists.view',
        ],
        'universities' => [
            'universities.create',
            'universities.view',
            'universities.update',
            'universities.delete',
            'universities.show',
            "approve_university.view",
            "manage_university.view",
            "un_approve_university.view",
            "oel_review.view",
            "oel_type.view"
        ],
        'courses' => [
            'courses.create',
            'courses.view',
            'courses.update',
            'courses.delete',
            'courses.show',
        ],
        'application_status' => [
            'application_status.create',
            'application_status.view',
            'application_status.update',
            'application_status.delete',
            'application_status.show',
        ],
        'offer_details' => [
            'offer_details.create',
            'offer_details.view',
            'offer_details.update',
            'offer_details.delete',
            'offer_details.show',
        ],
        'visa_application' => [
            'visa_application.create',
            'visa_application.view',
            'visa_application.update',
            'visa_application.delete',
            'visa_application.show',
        ],
        'visa_status' => [
            'visa_status.create',
            'visa_status.view',
            'visa_status.update',
            'visa_status.delete',
            'visa_status.show',
        ],
        'fee_details' => [
            'fee_details.create',
            'fee_details.view',
            'fee_details.update',
            'fee_details.delete',
            'fee_details.show',
        ],
        'flight_details' => [
            'flight_details.create',
            'flight_details.view',
            'flight_details.update',
            'flight_details.delete',
            'flight_details.show',
        ],
        'take_off' => [
            'take_off.create',
            'take_off.view',
            'take_off.update',
            'take_off.delete',
            'take_off.show',
        ],
        'boarding' => [
            'boarding.create',
            'boarding.view',
            'boarding.update',
            'boarding.delete',
            'boarding.show',
        ],
        'done' => [
            'done.show',
            'done.view',
        ],
        'impersonate' => [
            'impersonate.view',
        ],
        'franchise' => [
            'franchise.create',
            'franchise.view',
            'franchise.update',
            'franchise.delete',
        ],
        'manage_oel_presentation' => [
            'manage_oel_presentation.create',
            'manage_oel_presentation.view',
            'manage_oel_presentation.update',
            'manage_oel_presentation.delete',
        ],
        'manage_oel_agreement_letter' => [
            'manage_oel_agreement_letter.create',
            'manage_oel_agreement_letter.view',
            'manage_oel_agreement_letter.update',
            'manage_oel_agreement_letter.delete',
        ],
        'manage_oel_pincode' => [
            'manage_oel_pincode.create',
            'manage_oel_pincode.view',
            'manage_oel_pincode.update',
            'manage_oel_pincode.delete',
        ],
        'admin' => [
            'admin.view',
        ],
        'universities' => [
            'universities.create',
            'universities.view',
            'universities.update',
            'universities.delete',
        ],
        'programs' => [
            'programs.create',
            'programs.view',
            'programs.update',
            'programs.delete',
            'approve_program.view',
            'manage_program.view',
            'program_level_details.view',
            'education_level.view',
            'program_level.view',
            'grading_scheme.view',
            'exams.view',
            'field_of_study.view',
            'subject.view',
            'manage_recommended_programs.view'
        ],
        'my_profile' => [
            'my_profile.create',
            'my_profile.view',
            'my_profile.update',
            'my_profile.delete',
        ],
        'applied_program' => [
            'applied_program.create',
            'applied_program.view',
            'applied_program.update',
            'applied_program.delete',
        ],
        'student' => [
            'student.create',
            'student.view',
            'student.update',
            'student.delete',
        ],
        'specializations' => [
            'specializations.create',
            'specializations.view',
            'specializations.update',
            'specializations.delete',
        ],
        'source' => [
            'source.create',
            'source.view',
            'source.update',
            'source.delete',
        ],
        'interest' => [
            'interest.create',
            'interest.view',
            'interest.update',
            'interest.delete',
        ],
        'country' => [
            'country.create',
            'country.view',
            'country.update',
            'country.delete',
        ],
        'state' => [
            'state.create',
            'state.view',
            'state.update',
            'state.delete',
        ],
        'visa' => [
            'visa.create',
            'visa.view',
            'visa.update',
            'visa.delete',
        ],
        'faq' => [
            'faq.create',
            'faq.view',
            'faq.update',
            'faq.delete',
        ],
        'visa_service' => [
            'visa_service.create',
            'visa_service.view',
            'visa_service.update',
            'visa_service.delete',
        ],
        'testimonial' => [
            'testimonial.create',
            'testimonial.view',
            'testimonial.update',
            'testimonial.delete',
        ],
        'blogs' => [
            'blogs.create',
            'blogs.view',
            'blogs.update',
            'blogs.delete',
        ],
        'messages' => [
            'messages.create',
            'messages.view',
            'messages.update',
            'messages.delete',
        ],
        'oel_apply' => [
            'oel_apply.create',
            'oel_apply.view',
            'oel_apply.update',
            'oel_apply.delete',
        ],
        'universities' => [
            "approve_university.view",
            "manage_university.view",
            "un_approve_university.view",
            "oel_review.view",
            "oel_type.view",
            "updation-manage-university.view",
        ],
        'scholorship' => [
            'scholorship.create',
            'scholorship.view',
            'scholorship.update',
            'scholorship.delete',
        ],
        'specializations' => [
            'specializations.create',
            'specializations.view',
            'specializations.update',
            'specializations.delete',
        ],
        'source' => [
            'source.create',
            'source.view',
            'source.update',
            'source.delete',
        ],
        'interested' => [
            'interested.create',
            'interested.view',
            'interested.update',
            'interested.delete',
        ],
        'country' => [
            'country.create',
            'country.view',
            'country.update',
            'country.delete',
        ],
        'country' => [
            'country.create',
            'country.view',
            'country.update',
            'country.delete',
        ],
        'province' => [
            'province.create',
            'province.view',
            'province.update',
            'province.delete',
        ],
        'visa_type' => [
            'visa_type.create',
            'visa_type.view',
            'visa_type.update',
            'visa_type.delete',
        ],
        'faq' => [
            'faq.create',
            'faq.view',
            'faq.update',
            'faq.delete',
        ],
        'education_lane' => [
            'education_lane.create',
            'education_lane.view',
            'education_lane.update',
            'education_lane.delete',
        ],
        'manage_blogs' => [
            'manage_blogs.create',
            'manage_blogs.view',
            'manage_blogs.update',
            'manage_blogs.delete',
        ],
        'vas_services' => [
            'vas_services.create',
            'vas_services.view',
            'vas_services.update',
            'vas_services.delete',
        ],
        'student_registration_fees' => [
            'student_registration_fees.create',
            'student_registration_fees.view',
            'student_registration_fees.update',
            'student_registration_fees.delete',
        ],
        'student_apply_question' => [
            'student_apply_question.create',
            'student_apply_question.view',
            'student_apply_question.update',
            'student_apply_question.delete',
        ],
        'student_assistance' => [
            'student_assistance.create',
            'student_assistance.view',
            'student_assistance.update',
            'student_assistance.delete',
        ],
        'student_enquiry_log' => [
            'student_enquiry_log.create',
            'student_enquiry_log.view',
            'student_enquiry_log.update',
            'student_enquiry_log.delete',
        ],
        'popular_student_guide' => [
            'popular_student_guide.create',
            'popular_student_guide.view',
            'popular_student_guide.update',
            'popular_student_guide.delete',
        ],
        'find_program_log' => [
            'find_program_log.create',
            'find_program_log.view',
            'find_program_log.update',
            'find_program_log.delete',
        ],
        'message_lead' => [
            'message_lead.create',
            'message_lead.view',
            'message_lead.update',
            'message_lead.delete',
        ],
        'message_franchise' => [
            'message_franchise.create',
            'message_franchise.view',
            'message_franchise.update',
            'message_franchise.delete',
        ],
        'message_student' => [
            'message_student.create',
            'message_student.view',
            'message_student.update',
            'message_student.delete',
        ],
        'outbox' => [
            'outbox.create',
            'outbox.view',
            'outbox.update',
            'outbox.delete',
        ],
        'trash' => [
            'trash.create',
            'trash.view',
            'trash.update',
            'trash.delete',
        ],
        'sms_template' => [
            'sms_template.create',
            'sms_template.view',
            'sms_template.update',
            'sms_template.delete',
        ],
      ],
];
